PicklistOptions:
  Quote Type: ["Direct"]
  Priority: ["High","Medium","Low"]
  Status: ["Not Started","In Progress","Completed","Completed Successfully","Completed Unsuccessfully"]
  Record Type: ["Onboarding","Health Check","Up-sell","Cross-Sell"]